apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespaces.nexusNs }}
  name: {{ include "nxrm-aws-resiliency.fullname" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "nxrm-aws-resiliency.labels" . | nindent 4 }}
spec:
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nxrm-aws-resiliency.fullname" . }}
                port:
                  number: {{ .Values.service.nexus.port }}
---
{{- if .Values.ingress.dockerIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespaces.nexusNs }}
  name: {{ include "nxrm-aws-resiliency.fullname" . }}-docker
  {{- with .Values.ingress.dockerIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "nxrm-aws-resiliency.labels" . | nindent 4 }}
spec:
  rules:
    {{- if .Values.ingress.dockerIngress.host }}
    - host: {{ .Values.ingress.dockerIngress.host }}
      http:
    {{- else}}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nxrm-aws-resiliency.fullname" . }}-docker
                port:
                  number: {{ .Values.service.docker.port }}
{{- end }}
