apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nxrm-aws-resiliency.fullname" . }}
  labels:
    {{- include "nxrm-aws-resiliency.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  volumeMode: Filesystem
  accessModes:
  - {{ .Values.pv.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}
  storageClassName: {{ include "nxrm-aws-resiliency.fullname" . }}-local-storage
  local:
    path: {{ .Values.pv.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          {{- range $zone  := .Values.pv.zones }}
          - {{ $zone }} 
          {{- end }}  
