apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespaces.nexusNs }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.role }}
  labels:
    {{- include "nxrm-aws-resiliency.labels" . | nindent 4 }}
---
{{- if .Values.externaldns.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.externaldns.name }}
  namespace: {{ .Values.namespaces.externaldnsNs }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.externaldns.role }}
  labels:
    {{- include "nxrm-aws-resiliency.labels" . | nindent 4 }}
{{- end }}
