apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespaces.nexusNamespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.role }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalDns.serviceAccount.name }}
  namespace: {{ .Values.namespaces.externaldnsNs }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.externalDns.serviceAccount.role }}
---
