apiVersion: v1
kind: Service
metadata:
  name: {{ include "nxrm-aws-resiliency.fullname" . }}
  namespace: {{ .Values.namespaces.nexusNs }}
  labels:
    {{- include "nxrm-aws-resiliency.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.nexus.type }}
  selector:
    {{- include "nxrm-aws-resiliency.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: {{ .Values.service.nexus.protocol }}
      port: {{ .Values.service.nexus.port }}
      targetPort: {{ .Values.service.nexus.targetPort }}
---
{{- if .Values.service.docker.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nxrm-aws-resiliency.fullname" . }}-docker
  namespace: {{ .Values.namespaces.nexusNs }}
  labels:
    {{- include "nxrm-aws-resiliency.labels" . | nindent 4 }}
spec:
  type:  {{ .Values.service.docker.type }}
  selector:
    {{- include "nxrm-aws-resiliency.selectorLabels" . | nindent 4 }}
  ports:
    - name: docker-service
      protocol: {{ .Values.service.docker.protocol }}
      port: {{ .Values.service.docker.port }}
      targetPort: {{ .Values.service.docker.targetPort }}
{{- end }}
