{{- if and .Values.metrics.enabled .Values.metrics.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "nexus.fullname" . }}
  labels:
    app.kubernetes.io/component: nexus
{{ include "nexus.labels" . | indent 4 }}
  {{- if .Values.nexus.extraLabels }}
    {{- with .Values.nexus.extraLabels }}
      {{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
    {{- with .Values.metrics.prometheusRules.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ template "nexus.fullname" . }}
      rules:
        {{- with .Values.metrics.prometheusRules.rules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}